// <auto-generated />
using System;
using AC.LargeAppliances.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AC.LargeAppliances.Migrations
{
    [DbContext(typeof(EcomDbContext))]
    [Migration("20260330110948_x23")]
    partial class x23
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AC.LargeAppliances.Models.Entities.Card", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CardIcon1Class")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CardIcon1Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CardIcon1Tittle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CardIcon2Class")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CardIcon2Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CardIcon2Tittle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CardIcon3Class")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CardIcon3Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CardIcon3Tittle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CardIcon4Class")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CardIcon4Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CardIcon4Tittle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CardIcon5Class")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CardIcon5Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CardIcon5Tittle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("AC.LargeAppliances.Models.Entities.Discount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiscountCount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SignButton")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleSpan")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Discounts");
                });

            modelBuilder.Entity("AC.LargeAppliances.Models.Entities.Sponsor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageAlt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tittle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sponsors");
                });

            modelBuilder.Entity("AC.LargeAppliances.Models.Entities.Store", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Stores");
                });
#pragma warning restore 612, 618
        }
    }
}
