// <auto-generated />
using System;
using AC.LargeAppliances.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AC.LargeAppliances.Migrations
{
    [DbContext(typeof(EcomDbContext))]
    [Migration("20260401104652_x2")]
    partial class x2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AC.LargeAppliances.Models.Entities.AboutPage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Features1Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Features1Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Features2Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Features2Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Features3Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Features3Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Features4Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Features4Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartnerDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartnerTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StoresDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StoresTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value1IconClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value1Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value2IconClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value2Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value3IconClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value3Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value4IconClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value4Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AboutPages");
                });

            modelBuilder.Entity("AC.LargeAppliances.Models.Entities.CardItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CardItems");
                });

            modelBuilder.Entity("AC.LargeAppliances.Models.Entities.Career", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Img")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Careers");
                });

            modelBuilder.Entity("AC.LargeAppliances.Models.Entities.ContactRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsReaded")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ContactRequests");
                });

            modelBuilder.Entity("AC.LargeAppliances.Models.Entities.Contactpage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BottomChatDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BottomChatImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BottomChatMail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BottomChatTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BottomDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BottomMapAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BottomMapDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BottomMapImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BottomMapTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BottomPhoneDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BottomPhoneImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BottomPhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BottomPhoneTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BottomTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ButtonTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Maps")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StoresDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StoresTittle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tittle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Contactpages");
                });

            modelBuilder.Entity("AC.LargeAppliances.Models.Entities.Discount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiscountCount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SignButton")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleSpan")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Discounts");
                });

            modelBuilder.Entity("AC.LargeAppliances.Models.Entities.DiscountRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsReaded")
                        .HasColumnType("bit");

                    b.Property<string>("MailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DiscountRequests");
                });

            modelBuilder.Entity("AC.LargeAppliances.Models.Entities.Sponsor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageAlt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tittle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sponsors");
                });

            modelBuilder.Entity("AC.LargeAppliances.Models.Entities.Store", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Stores");
                });

            modelBuilder.Entity("AC.LargeAppliances.Models.Entities.Term", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Img")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Policy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Terms");
                });
#pragma warning restore 612, 618
        }
    }
}
